import Head from 'next/head'
import {
  Container,
  Main,
  Title,
  Description,
  CodeTag,
} from '../components/sharedstyles'
import Cards from '../components/cards'
import { getRestApiData } from '../utils/getRestApiData'
import type { RootState } from '../../app/store'
import { useSelector, useDispatch } from 'react-redux'
import { decrement, increment } from '../slices/testSlice'

interface dataItem {
  thisKeyDoesNotExistOnThisObject: string;
  buildingaddress__c: string;
  productcode: string;
  city__c: string;
  state__c: sting;
}

export default function Home( props: any ) {
  const resJson : dataItem[] = props.resJson;
  
  const count = useSelector((state: RootState) => state.test.value)
  const dispatch = useDispatch()
  return (
    <Container>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        <Title>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </Title>

        <Description>
          Get started by editing
          <CodeTag>pages/index.tsx</CodeTag>
        </Description>

        <Cards />
        <div>
          <button
            aria-label="Increment value"
            onClick={() => dispatch(increment())}
          >
            Increment
          </button>
          <span>{count}</span>
          <button
            aria-label="Decrement value"
            onClick={() => dispatch(decrement())}
          >
            Decrement
          </button>
        </div>
        <div>
          {
            resJson ? resJson.map((apt:dataItem, i:number)=>{
              return(
                <div key={i}>
                  <div>{apt.buildingaddress__c}</div>
                  <div>Apartment {apt.productcode}</div>
                  <div>{apt.city__c + ", " + apt.state__c + ", 12345"}</div>
                </div>
              )
            })  : <div>NO DATA FOUND</div>
          }
        </div>
      </Main>
    </Container>
  )
}

export async function getStaticProps() {
  const resJson = await getRestApiData()
  return {
    props: {
      resJson:resJson
    }
  }
}
